version: '3.8'
services:
  container-deployer-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/container-deployer-manager
      - /container-deployer-manager/node_modules
    environment:
      - SERVER_PORT=8080
      - DOCKER_ENDPOINT=unix:///var/run/docker.sock
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
