// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: deployer.proto

package deployer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DeployerServiceClient is the client API for DeployerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeployerServiceClient interface {
	// Sends a deployment request to the server
	DeployContainer(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error)
}

type deployerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployerServiceClient(cc grpc.ClientConnInterface) DeployerServiceClient {
	return &deployerServiceClient{cc}
}

func (c *deployerServiceClient) DeployContainer(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployResponse, error) {
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, "/DeployerService/DeployContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployerServiceServer is the server API for DeployerService service.
// All implementations must embed UnimplementedDeployerServiceServer
// for forward compatibility
type DeployerServiceServer interface {
	// Sends a deployment request to the server
	DeployContainer(context.Context, *DeployRequest) (*DeployResponse, error)
	mustEmbedUnimplementedDeployerServiceServer()
}

// UnimplementedDeployerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeployerServiceServer struct {
}

func (UnimplementedDeployerServiceServer) DeployContainer(context.Context, *DeployRequest) (*DeployResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployContainer not implemented")
}
func (UnimplementedDeployerServiceServer) mustEmbedUnimplementedDeployerServiceServer() {}

// UnsafeDeployerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeployerServiceServer will
// result in compilation errors.
type UnsafeDeployerServiceServer interface {
	mustEmbedUnimplementedDeployerServiceServer()
}

func RegisterDeployerServiceServer(s grpc.ServiceRegistrar, srv DeployerServiceServer) {
	s.RegisterService(&DeployerService_ServiceDesc, srv)
}

func _DeployerService_DeployContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).DeployContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DeployerService/DeployContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).DeployContainer(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeployerService_ServiceDesc is the grpc.ServiceDesc for DeployerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeployerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DeployerService",
	HandlerType: (*DeployerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployContainer",
			Handler:    _DeployerService_DeployContainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployer.proto",
}
